base_config: config/xlmroberta.yaml

options:
    search_method: random
    # Search the model architecture
    hidden_size:
        - 768
        - 324
    bottleneck_size:
        - 768
        - 324
    search_mlp: true
    # Search weights for the tag loss
    class_weights:
        target_tags:
            lower: 1
            upper: 10
        gap_tags:
            lower: 1
            upper: 20
        source_tags: null
    # Search the sentence level objective
    search_hter: true
    search_sentence_loss_weight: true
    sentence_loss_weight:
        lower: 1
        upper: 10
