base_config: config/xlmroberta.yaml

options:
    search_method: random
    hidden_size:
        - 768
        - 324
    bottleneck_size:
        - 768
        - 324
    search_mlp: true
    search_word_level: true
    search_sentence_loss_weight: true
    sentence_loss_weight:
        lower: 1
        upper: 10
